enum authorities {
    DEFAULT = "DEFAULT",
    USER_MODIFY = "USER_MODIFY",
    USER_DEACTIVATE = "USER_DEACTIVATE",
    SEE_DASHBOARD = "SEE_DASHBOARD",
    USER_READ = "USER_READ",
    USER_CREATE = "USER_CREATE",
    USER_VIEW = "USER_VIEW",
    EVENT_CREATE = "EVENT_CREATE",
    EVENT_VIEW = "EVENT_VIEW",
    EVENT_MODIFY = "EVENT_MODIFY",
    EVENT_DELETE = "EVENT_DELETE",

}

export default authorities;
